language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: "leochans-github"

script:
  # JaCoCo is used to have code coverage, "-Pcoverage" activates the maven profile in the pom.xml
  - mvn clean verify sonar:sonar -Pcoverage

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

jdk:
  - oraclejdk8
  - oraclejdk11
  - openjdk8
  - openjdk11
