spring:
  profiles:
    active: @activeProfile@
  application:
    name: @artifactId@-@activeProfile@
  jackson:
    serialization:
      write_date_timestamps_as_nanoseconds: false # serialize LocalDateTime with ISO local date time format